public class ApplicationWrapper {
    @AuraEnabled public String applicationName;
    @AuraEnabled public String studentName;
    @AuraEnabled public String email;
    @AuraEnabled public String role;
    @AuraEnabled public String status;
    @AuraEnabled public String note;
    @AuraEnabled public Date lastDate;
    @AuraEnabled public Boolean applied;
    @AuraEnabled public String companyName;
}